version: '3'
services:
  redis-service:
    image: "redis"
    networks:
      - backend-network
    volumes:
      - "redis-volume:/data"
  web-service:
    build: ./web
    environment:
      - REDIS_URL=redis://redis-service:6379
    ports:
      - "80:5000"
    networks:
      - backend-network
    depends_on:
      - redis-service
  
  test-service:
    profiles:
      - testing
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    environment:
      - REDIS_URL=redis://redis-service:6379
      - FLASK_URL=http://web-service:5000
    networks:
      - backend-network
    depends_on:
      - redis-service
      - web-service
    command: >
      sh -c 'python -m pytest test/e2e/ -vv
      --redis-url $$REDIS_URL
      --flask-url $$FLASK_URL'

networks:
  backend-network:

volumes:
  redis-volume:
    
